[build]
  base = "/"
  publish = "dist"
  command = "pnpm generate"

[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "20"

[context.production]
  environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200